name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@v1.5.2
        with:
          default: true
          ldproxy: true
      - name: Run cargo check
        run: cargo check
